### ISSUE TITLE
#14 Decide on colour scheme

### ISSUE THREAD

**Issue by bajancode** [the-collab-lab/tcl-31-smart-shopping-list#36]
Likely need green, yellow, red and grey (grey for inactive)

Will be used most prominently in checkboxes, but also possibly in other areas such as the welcome new list buttons.

-Warm colours
-Check with accessibility tool to make sure they are okay ie. https://accessible-colors.com/
-Expecting a white or very slightly off-white background

**Comment by andreamartz** [comment]
I am not clear on what you want me to do. I didn't know until early this morning that this issue had been created. Now I see that the issue says to "decide on a color scheme", and similarly in Slack Victoria mentioned, "we were having a hard time deciding the colours, and remembered you had already put some thought into the psychology of colours etc, so would you be able to decide on a first attempted colour scheme".  

I'm a bit confused, because it looks like you already decided on colors. 

It looks like everyone decided on two things:
* warm colors and
* using green, yellow, red, and gray

Another point of confusion: Green and gray are not warm. Yellow and red are.

Are you asking me to focus not on an overall color scheme, but just on the "soon", "kind of soon", "not soon" colors? If so, why not just use the ones on page 8 in Canva? Or something close to them that is already a shade in Material UI? 

It sounds like none of the work I did yesterday (i.e., coming up with the orange and white palette and related sample design elements before I knew you had decided on a color scheme already) will be relevant. I don't want to put in more hours until I am more clear on what you want me to do. 

Please remember that I was not at the first meeting, because it was scheduled for a time I when I had a doctor's appointment. I showed up for as much as I could of the second meeting, and was confused for a lot of it, because I couldn't tell from Slack or Canva (and now here) what decisions had already been made.

**Comment by bajancode** [comment]
![Screenshot_20211120-111917](https://user-images.githubusercontent.com/52695922/142731731-1100b287-ea80-4c39-991f-88de044646f5.jpg)

This is a great example of how much we can still learn and benefit from communications!

You responded to this thread on Slack before doing your work where we asked you to work on a colour scheme. It also mentions high level details are provided on the project board, and assigned it to you on GitHub as well which typically would send you some sort of notification. Maybe we should have asked you to reword your understanding of the task to make sure we were on the same page?

Any ideas for how you would you have liked us to communicate this to you better? Other than using the two main communication channels we typically use? I think our hours were a bit challenging this week so while a one on one call would have been ideal I don't think was in the cards!

I'm not available to hop on a call before our meeting tomorrow, but I agree we don't want to waste your time (or anyone's!). Maybe check on Slack if Aidan or Gaby could help you, that's usually where this type of more detailed conversation would take place!

**Comment by bajancode** [comment]
This is a great example of how much we can still learn and benefit from communications!

You responded to the thread on Slack (created Nov 18 11:46am AT) before doing the work where we asked you to work on a colour scheme. It also mentions high level details are provided on the project board, and assigned it to you on GitHub as well which typically would send you some sort of notification. Maybe we should have asked you to reword your understanding of the task to make sure we were on the same page?

Any ideas for how you would you have liked us to communicate this to you better? Other than using the two main communication channels we typically use? I think our hours were a bit challenging this week so while a one on one call would have been ideal I don't think was in the cards!

I'm not available to hop on a call before our meeting tomorrow, but I agree we don't want to waste your time (or anyone's!). Maybe check on Slack if Aidan or Gaby could help you, that's usually where this type of more detailed conversation would take place!

**Comment by andreamartz** [comment]
Thanks Victoria. Much appreciated.

To be clear, I never expected a one-on-one meeting with anyone.  : )

The main thing that would help is a list of documented decisions about things we want and things we decided against would be helpful. This list would include decisions about colors, design elements, shapes, sizes, fonts, what goes on which page, combining two pages into one and what that would look like...just every decision made of any sort. 

Also, since none of us (that I know of) are trained as designers, defining terms like "color scheme" would be helpful. In my experience, a color scheme refers to the whole website and some basic (at least)  principles of color psychology are considered to turn the consensus about tone / feeling words into colors. That's why, before I started researching and brainstorming yesterday, I suggested focusing on only a couple of tone words that we mostly seemed to have in common (i.e., clean and fun). That is to say, I was not focusing on "cool" or "warm colors" or "calm" or "effortless", etc. from our lists. I did not see "smart" on anyone's list, but it sounds like that became an important design word at some point.

I see a lot of ideas in the Canva "mood board", but I've always used mood boards as sort of a big online poster where everyone slaps design ideas on and then we come to a consensus. So, to me our mood board looks like a series of potential ideas in both picture and text form. I didn't realize that so many decisions had been made. I don't see any indication of decisions in Canva actually.

You mentioned above that "...It also mentions high level details are provided on the project board, and assigned it to you on GitHub as well" 
I also see this in Slack: "I wrote a few more details on the project board, which you can make into a proper user story / acceptable criteria if you would like!! "
* Where are the high level details on the project board? I see the TCL-provided issue on the board, but I don't see any other team-specific issues on the board. I do see them in Issues, but not on the board. 
* As for notifying me in Slack that I was assigned to this GitHub issue, I only see in Slack on Thursday morning where you mentioned, "everyone is going to put the details of their project / task on the github project board". So, I thought everyone was supposed to post their own issue. That thought was reinforced by, "...which you can make into a proper user story..." (aka, an issue).I hadn't gotten to writing an issue yet, but I thought that was a task for me to do. Is there another place where it says that the issue assigned to me had been posted?

That's all that comes to mind right now to help make communication clearer from my end.

**Comment by bajancode** [comment]
You have high standards and expectations which is a huge asset in many
situations! Some things aren't realistic with the timeframes and the
constraints for this short group project, a design doc would take all week
at least and we only have a few hours each.

Not a lot is firmly decided, there's a lot of flexibility/creativity
required this last week or so, but good to ask questions as you're doing if
you're unable to get it done without more info!

Maybe you'll be able to get hold of another team member before Sunday's
meeting, if not it's fine, I know you're working hard at your new job and
it's a lot so maybe it's more a chance for some rest and we will do a good
push in the final week!

This can be discussed further in Slack, this seems like more of a Slack
than a GitHub conversation. Feel free to start a new thread with some of
these specifics if you'd like, though I'm not sure everyone's availability
this weekend! Mine is next to zero!

**Comment by andreamartz** [comment]
I may have been unclear in my own communication. **Please know that I am definitely not asking for anything that would take anywhere near a week**. Just a bulleted list of decisions made by the team would be a good central reference for everyone. Maybe no one has time to even document the decisions made in the meetings. If that's the case, it will be difficult for me to contribute. That's fine with me if it's fine with everyone else. I just don't want to let you all down.

**Comment by andreamartz** [comment]
**Yellow** (MUI Yellow 800 with black #000000 text)

- White text does not contrast enough with any shade/hue/tint of yellow unfortunately. Black does, though.
- ![Screen Shot 2021-11-21 at 7 41 31 PM](https://user-images.githubusercontent.com/14165788/142788868-e70e7f98-c98e-4ff7-badc-1a58017484c5.png)

**Red** (MUI Red 800 with black #000000 or white #ffffff text)
- White text has enough contrast. Black does too as long as the font size is big enough.
- ![Screen Shot 2021-11-21 at 7 43 21 PM](https://user-images.githubusercontent.com/14165788/142788956-4bd19479-a31c-4fd1-9798-59e02e1870ec.png)

**Green** (MUI Green 800 with 
- White text has enough contrast. Black does too as long as the font size is big enough.
- ![Screen Shot 2021-11-21 at 7 45 45 PM](https://user-images.githubusercontent.com/14165788/142789107-2de01788-7065-4752-8b9a-2909efd057cc.png)

**Comment by bajancode** [comment]
This is great! Colours looks coherent and classic and I could see them going well with the orange.

I guess the question now is should we be using black for all for consistency as it seems the most accessible as well? @gabynr @aidantorrence

**Comment by gabynr** [comment]
I think that the black font color is ok when it is a sentence or paragraph. Like text on the Home page, but I prefer the white font for the button when the button has color. As the button on the home page is color orange.  But I don't know if what I say is ok.

**Comment by bajancode** [comment]
Thanks Andrea, I have started implementing these! 

The only difference is I'm going to use #ff8601 for orange, as it's the one Aidan used for the Welcome page. I checked and still works with the others and is accessible for how we'll be using it!
